### ISSUE TITLE
Use the `atom-text-editor` tag instead of the `editor` class.

### ISSUE THREAD

**Issue by brenoc** [R1ZZU/spacegray-eighties-dark-syntax#1]
In index.less: Use the `atom-text-editor` tag instead of the `editor` class.

**Comment by R1ZZU** [comment]
Hi, @brenoc!
Thanks for writing in, but I already unpublished this theme from apm :crying_cat_face: 

There is a couple of similar syntax themes:
* [tomorrow-night-eighties theme](https://atom.io/themes/tomorrow-night-eighties)
* [Tomorrow Night Eighties Atom Syntax Theme](https://atom.io/themes/tomorrow-night-eighties-syntax)

**Comment by brenoc** [comment]
@R1ZZU oh, sorry, about that! This theme was the most closer to SpaceGray. Thanks for you reply :)
